FROM python:3.12-slim

#crear carpeta de trabajo 
WORKDIR /app

#copia de requeremientos 
COPY requirements.txt .

#intalalos
RUN pip install --no-cache-dir -r requirements.txt

#copiar codigo del proyecto
COPY ./app ./app

#exponer puesto a trabajar 
EXPOSE 5000

#Comandos para ejecutar fastapi
CMD [ "uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]
